imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    profiler:
        enabled: false
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_base_urls: http://localhost:5803/web/
        assets_base_urls: http://test.log.towerleisure.nl/web/
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    handlers:
        guesty:
            # log all messages (since debug is the lowest level)
            level:    alert
            type:     stream
            path:     '%kernel.logs_dir%/guesty.log'


parameters:
    images.listing: "%kernel.root_dir%/../web/uploads/images/listing"
    images.furniture: "%kernel.root_dir%/../web/uploads/images/furniture"
    images.reportissue: "%kernel.root_dir%/../web/uploads/images/reportissue"
    images.reportplanning: "%kernel.root_dir%/../web/uploads/images/reportplanning"

fos_user:
    db_driver: orm # otros valores válidos son 'mongodb', 'couchdb' and 'propel' depende de que gestor utilices
    firewall_name: main # Es el firewall configurado en el archivo security.yml en el paso 4
    user_class: Manage\RestaurantBundle\Entity\User # Es el usuario de tu aplicación creado en el paso 3 y la introducción
    from_email:
        address: "noreply@yourcompany.com"
        sender_name: "No Reply"