restaurant:
    resource: "@RestaurantBundle/Controller/"
    type:     annotation
    prefix: /
    schemes: [https]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes: [https]
