# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        #Manage\AdminBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}
   
    role_hierarchy:
        ROLE_CLEANING:    [ROLE_CLEANING_LIST]
        ROLE_MAINTENANCE: [ROLE_CLEANING, ROLE_MAINTENANCE_LIST, ROLE_MAINTENANCE_EDIT]
        ROLE_SERVICE:     [ROLE_CLEANING, ROLE_LONGSTAY_EDIT, ROLE_MAINTENANCE, ROLE_MAINTENANCE_PLANNING, ROLE_INVENTORY_SHOW, ROLE_INVENTORY_EDIT]
        ROLE_RECEPTION:   [ROLE_CLEANING, ROLE_LONGSTAY_EDIT, ROLE_HOTEL_FORM, ROLE_MAINTENANCE_LIST]
        ROLE_SUPER_ADMIN: [ROLE_USER_ADMIN, ROLE_FORMS_SETTINGS, ROLE_GUESTY, ROLE_HOTEL_KASBOEK, ROLE_RECEPTION, ROLE_SERVICE]
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        #email:
            #entity: {class: Manage\AdminBundle\Entity\User, property: email}
   
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/login$
            security: false

        command:
            pattern:  ^/command/*
            anonymous: ~
            security: false

        guesty:
            pattern:  ^/guesty/*
            anonymous: ~
            security: false

        rule:
            pattern:  ^/rule/execute
            anonymous: ~
            security: false

        hoook:
            pattern:  ^/rule/hook/*
            anonymous: ~
            security: false

        webhoook:
            pattern:  ^/hook/*
            anonymous: ~
            security: false
            
        external:
            pattern:  ^/external/*
            anonymous: ~
            security: false
            
        cleanness:
            pattern:  ^/cleanness/*
            anonymous: ~
            security: false


#        admin:
#            pattern:  ^/*
#            provider: email
#            form_login:
#                login_path: login
#                check_path: login_check
#                default_target_path: home
#            logout:
#                path: logout
#                target: login
#
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/command, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/guesty/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/rule/hook/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/rule/execute, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/hook/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/reportplanning/createissue/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/reportissue/new, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/reportissue, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/*, roles: ROLE_USER, requires_channel: http}
