<?php

namespace Manage\RestaurantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResportIssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportIssueRepository extends EntityRepository
{
    public function getListActiveIssue(){
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM RestaurantBundle:ReportIssue r WHERE r.status !=:status ORDER BY r.dated DESC, r.reportedat DESC')
            ->setParameter("status", 'Afgerond')
            ->getResult();
    }
}
