<?php

namespace Manage\RestaurantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RFurnitureTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RFurnitureTagsRepository extends EntityRepository
{
}
